- name: ubuntu install
  apt:
    name: "{{item}}"
    update_cache: yes
    state: present
  when: ansible_facts['os_family'] == "Debian"
  loop: "{{  package_list  }}"
  notify:
    - restart apache2